### ISSUE TITLE
Variables in circuits?

### ISSUE THREAD

**Issue by hanyuone** [LogicodeLang/Logicode#12]
I would like to suggest a new feature: variables in circuits.

They would work like this:

```
circ test(a,b)->[
  var in_circ=a&b
  in_circ+1
]
out test(1,1)
```

Which would then output `11`.

**Comment by somebody1234** [comment]
Oh yay more syntax, I'll work on it once I get back on by laptop.

Multiline circuits looks like the bigger feature here, once that's done it should work fine since circuits have their own scope anyway :P

**Comment by hanyuone** [comment]
While we're on the topic of improving syntax, this doesn't work:

```
a[t][h]
```

We should probably improve the parser so that this works.

I'll work on this bit - I just have no idea where to start.

**Comment by bortkiewicz** [comment]
Uh... isn't there a "command separator" like ; as in Python? This would make it easier because then everything can first be compressed to `circ test(a,b)->var in_circ=a&b;in_circ+1`. The parser would split it and recursively parse them.

And isn't there a "return command" to specify the parser WHAT to return from a circuit?

**Comment by somebody1234** [comment]
@DerpfacePython Should be simple, I'll do it tomorrow
@testitem That should parse as:

```
circ test(a,b)->var in_circ=a&b
in_circ+1
```

IMO

@DerpfacePython What do you think about having a command separator though?

**Comment by bortkiewicz** [comment]
Well the com sep shouldn't be as common as in C++ and like that, one-per-line

**Comment by hanyuone** [comment]
A command separator would be nice, but IMO we should have both multi-line functions and command separators.

**Comment by bortkiewicz** [comment]
Well MLFs could work by compressing the code block in the brackets.

**Comment by somebody1234** [comment]
@DerpfacePython So we use `;` for command separator?

**Comment by hanyuone** [comment]
@somebody1234 Ummm... yeah, sure, why not. I'm thinking of a better separator, though.

Maybe use `|` as a separator, change OR to `?` and change the random bit to `*`?

**Comment by somebody1234** [comment]
IDK, `|` is or in most languages, just change the regexes when you've decided

**Comment by hanyuone** [comment]
But `;` seems really mainstream...

Also, `cond`s aren't supported in circuits.

**Comment by somebody1234** [comment]
@DerpfacePython Yeah, what about `cond`s and `circuits`

**Comment by hanyuone** [comment]
So something like this:

```
circ asdf(a)->[
    var a=0+a[t]
    cond a->asdf(a)/0
]
```

returns a `KeyError`.

**Comment by somebody1234** [comment]
Oh, you want `cond`s, brb fixing

EDIT: @DerpfacePython should be fixed now

**Comment by hanyuone** [comment]
Also, `[t]` doesn't work - something like

```
var a=1110
out a[t]
```

outputs `0` instead of `110`.

**Comment by somebody1234** [comment]
@DerpfacePython Oh wait whoops

**Comment by hanyuone** [comment]
What? I thought `[t]` was all bits other than the 1st one.

**Comment by somebody1234** [comment]
@DerpfacePython Sorry about that, will fix when I get home in ~3h

**Comment by hanyuone** [comment]
Nah, DW about the last problem - I fixed it.

**Comment by somebody1234** [comment]
@DerpfacePython Actually fixed now
