### ISSUE TITLE
Logic gates... more?

### ISSUE THREAD

**Issue by bortkiewicz** [LogicodeLang/Logicode#13]
the README says:

> Because of that, the only built-in commands are AND, OR and NOT, and you make the rest.

Why not XOR NOR NAND etc

**Comment by bortkiewicz** [comment]
As well as that, tests/all_logic_gates.lgc shouldn't print anything in the first place since there was no out statements.

**Comment by somebody1234** [comment]
@testitem @DerpfacePython is the one making the implementation, plus AND+OR+NOT already makes it pretty much TC.

**Comment by hanyuone** [comment]
@testitem It's not meant to print anything - they're just meant to be circuits. See [this](http://codegolf.stackexchange.com/questions/82938/golf-all-the-16-logic-gates-with-2-inputs-and-1-output) for more details.

Also, those three logic gates (AND, OR, NOT) are enough to made all other logic gates without making everything too tedious.
