### ISSUE TITLE
Please enable wikis

### ISSUE THREAD

**Issue by bortkiewicz** [LogicodeLang/Logicode#18]
see #4 last comment

**Comment by hanyuone** [comment]
You do it...

**Comment by bortkiewicz** [comment]
I couldn't.

**Comment by bortkiewicz** [comment]
If i do wiki it redirects me to code. collaborator-only or what?

**Comment by bortkiewicz** [comment]
just go to "settings", i don't have access to the tab

**Comment by hanyuone** [comment]
Oh yeah, whoops. I'll make a new page.

**Comment by bortkiewicz** [comment]
Are you doing it? I couldn't see the wiki!

**Comment by somebody1234** [comment]
@DerpfacePython Go to Settings (last tab) -> Uncheck "Restrict edits to collaborators only"

**Comment by hanyuone** [comment]
@testitem You should be good to go now.
