### ISSUE TITLE
Line 571 clarification (logicode.py)

### ISSUE THREAD

**Issue by bortkiewicz** [LogicodeLang/Logicode#27]
@somebody1234

Line 571 says: 

```
    code = raw_input("Enter program: ")
```

Wouldn't this only read one line of code?

**Comment by testitem** [comment]
Is it fixed or not? There hasn't been many replies for a while.

**Comment by somebody1234** [comment]
Yeah, use:  

```
sys.stdout.write("\nLogicode> ")
sys.stdin.read()
```

To read until EOF (<kbd>Ctrl</kbd>+<kbd>D</kbd>)
