### ISSUE TITLE
Tk-based LGC editor?

### ISSUE THREAD

**Issue by bortkiewicz** [LogicodeLang/Logicode#9]
Would there be a _specific_ code editor for .LGC files, or does the user have to edit it in some kind of other code shell like the Python editor or Notepad?

**Comment by bortkiewicz** [comment]
If the answer is "yes", prepare to set some months of time doing this

**Comment by somebody1234** [comment]
Well, hardly any languages have an IDE, plus it's way easier to just make syntaxes for code editors sooo...

**Comment by hanyuone** [comment]
When this becomes big, maybe we can make a syntax highlighter for Atom?

**Comment by bortkiewicz** [comment]
Yeaaaaahhhhh....

**Comment by bortkiewicz** [comment]
> Well, hardly any languages have an IDE, plus it's way easier to just make syntaxes for code editors sooo...

Well then how come the language YOU are using, Python, has an IDE?

**Comment by bortkiewicz** [comment]
Oh and also, this is cross-python compatible, is it? Im not used to Python 2 "ttk"

**Comment by hanyuone** [comment]
But we don't need an IDE... not yet, anyway. We still need to iron out all of the bugs.

**Comment by somebody1234** [comment]
@testitem How many million people do you think use Python?

**Comment by somebody1234** [comment]
@testitem Python is one of the most popular scripting languages, how would you expect it not to have an DE

**Comment by somebody1234** [comment]
How many hobby languages have their own IDE?

**Comment by bortkiewicz** [comment]
Java doesn't have its own specific IDE. Yet it is the most popular programming language. C and C++ doesn't either. Python, yet only the fifth most popular, has an IDE. Uh.. ttk?

**Comment by somebody1234** [comment]
@testitem Java has IntelliJ, C/C++ have Visual Studio (well, kinda)

**Comment by bortkiewicz** [comment]
Oh well here is my current IDE. Don't expect it to do anything nice :(

```
# PYTHON 3 ONLY

from tkinter import *
from tkinter.ttk import *
from tkinter.filedialog import *
from tkinter.messagebox import *

def new():
    # TODO
    pass

def openf():
    global textbox
    filename = askopenfilename()
    textbox.insert('1.0',open(filename).read())

def save():
    global textbox
    filename = asksaveasfilename()
    with open(filename, 'w') as f:
        f.write(textbox.get('1.0','end'))

def saverun():
    save()
    run()
    return

def run():
    # TODO
    pass

root = Tk()
root.option_add('*tearOff', FALSE)
mainBar = Menu(root)
fileMenu = Menu(mainBar)
#editMenu = Menu(mainBar)
#formMenu = Menu(mainBar)
runMenu = Menu(mainBar)
fileMenu.add_command(label="New File", command=new)
fileMenu.add_command(label="Open File", command=openf)
fileMenu.add_command(label="Save as", command=save)
runMenu.add_command(label="Save and Run", command=saverun)
runMenu.add_command(label="Just Run", command=run)
mainBar.add_cascade(menu=fileMenu, label="File")
#mainBar.add_cascade(menu=editMenu, label="Edit")
#mainBar.add_cascade(menu=formMenu, label="(Re)Format")
mainBar.add_cascade(menu=runMenu, label="Run")
root.config(menu=mainBar)
textbox = Text(root, width=140, height=120, wrap="word")
textbox.grid()
root.mainloop()
```

**Comment by bortkiewicz** [comment]
I do NOT know how to port the module names into python 2.

**Comment by somebody1234** [comment]
This doesn't need an IDE, I use Sublime literally all the time, mostly for JS/Python, and it's fairly easy to make a syntax for Sublime.

**Comment by hanyuone** [comment]
@testitem Could you add the information from the wiki and stuff (i.e. the documentation of the language) into the website (i.e. the branch `gh-pages`)?

(Also, I know you copied and pasted.)

**Comment by bortkiewicz** [comment]
Sure. Didn't i load the README into the html?

**Comment by hanyuone** [comment]
@testitem Yeah, just split it up like you did in the wiki. If you can, maybe do something like [this](https://docs.cheddar.vihan.org). Once you've got the thing started, I'll help out with the rest.

**Comment by bortkiewicz** [comment]
When am I going to have write access??? (Wait who is the admin @DerpfacePython or @somebody1234 ?)

**Comment by schas002** [comment]
@testitem DerpfacePython it is, I'm sure.

**Comment by hanyuone** [comment]
@testitem I'm writing an IDE right now (using Electron) - it'll just have a basic syntax highlighter and a "Run" button, which takes, like, a few days to whip up. I'll post the basic code later.

**Comment by bortkiewicz** [comment]
Can I continue on my Tkinter IDE? And are you writing it in Python? I am starting to get REAL cranked up with this JS, HTML and CSS stuff.

**Comment by bortkiewicz** [comment]
P.S. @DerpfacePython What is your email address?

**Comment by schas002** [comment]
DerpfacePython wishes to leave his email hidden. 😜

**Comment by schas002** [comment]
Or not, maybe. Who knows...

**Comment by testitem** [comment]
If you annoy me enough I could delete your post, @schas002 .

**Comment by schas002** [comment]
UGH, SORRY! Would try to never do again.

**Comment by hanyuone** [comment]
@testitem Why do you need my email? You can just contact me here. We can both work on IDEs separately, but I have a feeling yours is going to be easier to make (seeing as the interpreter itself is written in Python).
